DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  order_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  order_start TIMESTAMP,
  order_end TIMESTAMP
);
